### ISSUE TITLE
Agregar aclaración en pagina 4 de la guía

### ISSUE THREAD

**Issue by ellamarina** [fnemina/cursos_UEFM#55]
Pagina 4 de la guía.

Localice dentro de la imagen el aeropuerto de cataratas del Iguazu.  (quizás se podría decir que al abrir la imagen están por defecto activados los polígonos vectores... que por ahora los ignoren... o algo por el estilo)

**Comment by fnemina** [comment]
Se eliminaron los vectores de las imágenes.
