### ISSUE TITLE
Tips para agregar como ayuda para alumno en página 5

### ISSUE THREAD

**Issue by ellamarina** [fnemina/cursos_UEFM#56]
Mida la longitud de la pista de aterrizaje del aeropuerto de cataratas del Iguazu (se puede recordar el uso de la herramienta zoom en este caso)

Halle las coordenadas en latitud y longitud de aeropuerto de cataratas del Iguazu. (se puede sugerir  desclickear la herramienta de medición o hacer clic en la  herramienta de selección, previo a realizar la medición)

Para obtener información sobre un pixel seleccione la pestana Pixel info , junto al Product explorer
(Figura 1.6), y posicionese sobre (agregar un pixel en vez de uno) en la imagen (sé que parece redundante pero al leerlo me parece mas completo)

**Comment by fnemina** [comment]
Las segerencias se van a vertir en los foros.
